### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by stichou** [rometsch/simdata#22]
I installed `disgrid` thanks to the command:
```
pip3 install git+https://github.com/rometsch/disgrid --user
```
(I used --user because I have not sudo rights)

However it seems that something went wrong during the installation because python3 is not able to find the package:
```
ModuleNotFoundError: No module named 'disgrid'
```
Do you know how to solve this issue ?

Thanks in advance :)

**Comment by rometsch** [comment]
Which python distribution did you use?
I tested it for various system using pip.

**Comment by stichou** [comment]
I use Python 3.6.8

**Comment by rometsch** [comment]
This might cause the issue.
I will look into how the new pyproject.toml file interacts with older version of python.

**Comment by rometsch** [comment]
Interestingly, the pyproject.toml file includes a requirement for python version >= 3.7
https://github.com/rometsch/disgrid/blob/c81934b0938a5f118c2539b7dfc9e75dcf54893f/pyproject.toml#L20

**Comment by rometsch** [comment]
I just encountered the same same problem within a docker container running on top of the ubuntu:22.04 container with pip install via the apt package `python3-pip`.

Running
`pip install --upgrade pip`
solved the issue for me.

A comment in [this thread](https://github.com/pypa/setuptools/issues/3269#issuecomment-1104815581) of the setuptools repo issues refers to some patches done to python by debian interfering.
This might cause the issue.

However, since we have a solution, this should not matter anymore.
